#!/usr/bin/env bash
# Configures an Ubuntu server to change localhost and facebook.com IP resolution

cp /etc/hosts ~/hosts.new
sed -i '/localhost/d' ~/hosts.new
sed -i '/facebook.com/d' ~/hosts.new
echo "127.0.0.2 localhost" >> ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
